server.servlet.context-path: /blog

spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:./build/blogdb
  username: username
  password: password
# connection pool use tomcat
  tomcat:
    maxActive: 10
    maxIdle: 10
    minIdle: 10
    initialSize: 10
    defaultAutoCommit: false
# h2 for debug tool
spring.h2.console:
  enabled: true
  path: /h2-console
  settings.web-allow-others: true

doma:
  dialect: H2
  naming: SNAKE_LOWER_CASE
